# Generated by Django 4.2.5 on 2023-11-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0005_alter_cruise_id_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cruise', models.CharField(max_length=255)),
                ('opinion', models.TextField()),
            ],
        ),
    ]
